version: '3.9'
services:
  rikada:
    build:
      context: .
    container_name: rikada
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"