version: "3"

services:
  rikada:
    build: .
    image: rikada
    ports:
      - "3000:3000"
    volumes:
      - ./next:/app

  json-server:
    image: json-server
    ports:
      - "5000:5000"
    volumes:
      - ./db:/data
    command: json-server --watch database.json

networks:
  default:
    name: host
