import Head from "next/head";
import SearchBox from "../component/mainpage/searchbox";
import NewProperty from "../component/mainpage/newproperty";
import CitiesProperty from "../component/mainpage/citiesproperty";
import Agents from "../component/mainpage/agents";
import SiteComments from "../component/mainpage/sitecomments";
import Articles from "../component/mainpage/articles";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="relative text-textColorBase">
        <SearchBox />
        <NewProperty />
        <CitiesProperty />
        <Agents />
        <SiteComments />
        <Articles />
      </main>
    </>
  );
}
