import Head from "next/head";
import SearchBox from "../component/mainpage/searchbox";
import NewProperty from "../component/mainpage/newproperty";
import CitiesProperty from "../component/mainpage/citiesproperty";
import Agents from "../component/mainpage/agents";
import SiteComments from "../component/mainpage/sitecomments";
import Articles from "../component/mainpage/articles";
import GetCitiesApi from "../api/cityApi";
import axios from "axios";
import { GET_CITIES } from "../siteconfig/constant";

export async function getStaticProps(){
  const citiesList = await axios.get(GET_CITIES);
  console.log(JSON.parse(JSON.stringify(citiesList.data)))
  return {props:{cities : JSON.parse(JSON.stringify(citiesList.data))}}
}
export default function Home({cities}) {
  console.log(cities)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="relative text-textColorBase">
        <SearchBox cities={cities}/>
        <NewProperty />
        <CitiesProperty />
        <Agents />
        <SiteComments />
        <Articles />
      </main>
    </>
  );
}
